### ISSUE TITLE
Add crossorigin property to elements

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/broccoli-sri-hash#1]
As suggested by @metromoxie adding crossorigin property:

https://twitter.com/metromoxie/status/613824343001268224

Suggestion:
- Accept an origin in the options passed into the plugin.
- Use origin to determine which URLs are remote to the page
- For script or link tags that don't have a `crossorigin` property set it to `crossorigin="anonymous"` if the resource isn't loaded from the current path.

Decide upon a method to exclude or include third party library code that should not have an integrity.

**Comment by jonathanKingston** [comment]
This should be now fixed with the latest release.

Thanks @metromoxie for raising this.

**Comment by joelweinberger** [comment]
Woo-hoo! Thanks for putting this in!

**Comment by jonathanKingston** [comment]
It only works with CDN URLs with an md5 hash.

Broccoli:

```
var sri = require('broccoli-sri-hash');

var test = sri('test/fixtures/input', {
  prefix: 'https://example.com/',
  crossorigin: 'anonymous'
});
```

HTML:

```
<script src="thing.js"></script>
<script src="https://example.com/thing-5e1978f9cfa158d9841d7b6d8a4e5c57.js"></script>
```

Output:

```
<script src="thing.js" integrity="sha256-oFeuE/P+XJMjkMS5pAPudQOMGJQ323nQt+DQ+9zbdAg= sha512-+EXjzt0I7g6BjvqqjkkboGyRlFSfIuyzY2SQ43HQKZBrHsjmRzEdjSHhiDzVs30nXL9H0tKw6WbMPc6RfzUumQ=="/></script>
<script src="https://example.com/thing-5e1978f9cfa158d9841d7b6d8a4e5c57.js" integrity="sha256-oFeuE/P+XJMjkMS5pAPudQOMGJQ323nQt+DQ+9zbdAg= sha512-+EXjzt0I7g6BjvqqjkkboGyRlFSfIuyzY2SQ43HQKZBrHsjmRzEdjSHhiDzVs30nXL9H0tKw6WbMPc6RfzUumQ==" crossorigin="anonymous" /></script>
```

Assuming `thing.js` matches `5e1978f9cfa158d9841d7b6d8a4e5c57` md5 sum check.

This is to prevent any content loaded in the HTML that may match file paths also in the websites assets. I might allow later the ability to whitelist and not check hashes on the URLs.
