### ISSUE TITLE
Does not take `base` tag into account.

### ISSUE THREAD

**Issue by rwjblue** [jonathanKingston/broccoli-sri-hash#12]
Currently, when processing `tests/index.html` that has:

```
<base href="/">
<script src="assets/vendor.js"></script>
```

We look for `tests/assets/vendor.js`, but we should be looking for `assets/vendor.js`.  This means that no `integrity=` attributes are added for `tests/index.html` (but they are properly added for `index.html`).  This is also causing the ember-cli-sri tests to fail (because none of the `<script>` or `<link>` tags get `integrity=` attributes added).

**Comment by rwjblue** [comment]
I really want to kill the damned `<base>` tag, but I think this needs to be taken into account here anyways.

**Comment by stefanpenner** [comment]
> I really want to kill the damned <base> tag, but I think this needs to be taken into account here anyways.

yes, we should have session soon to kill it.
